server:
  port: 9091
  servlet:
    context-path: /api
wechat:
  account: gh_0f38c1055be5
  appid: wx22fe4cc0635b989d
  appsecret: d3afbeefd799e8e7b71bd5e854e692b4
spring:
  application:
    name: rjz-springboot
  datasource:
    url: jdbc:mysql://47.244.169.240:65533/rjz_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: Shuairr1215.
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  file:
    name: ./logs/${random.uuid}.log
  level:
    root: INFO
