server:
  port: 9091
  servlet:
    context-path: /api
niushuai:
  rjz:
    title: rjz账单-
    content: rjz账单-
    # spring cron 不支持 L W D
    excel-cron: 0 30 21 28-31 * ?
#小程序配置
wechat:
  account: gh_0f38c1055be5
  appid: wxd484501fb9ebeb22
  appsecret: 7aac14ef8476bd36a6e45a3ff8a4b1de
#公众号配置
wx:
  mp:
    app-id: wx53f824b370901a05
    secret: 460ee51fdb4edcf26dac5101abb8ecd5
    aes-key: XU0sZTr2zl09Hd2CWBEtiHYLEDZqIfRuz902uMrFxXO
    token: rjzss
spring:
  application:
    name: rjz-springboot
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rjz_db_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: niushuai233
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 30000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      read-only: false
  # 邮件
  mail:
    # 主机
    protocol: smtp
    host: smtp.qq.com
    username: shuai.niu@foxmail.com
    password: xggumcsfhbhthhii
    port: 465
# 日志
logging:
  file:
    name: ./logs/${random.uuid}.log
  level:
    root: INFO
    cc.niushuai: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    me.chanjar.weixin: DEBUG